services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: truco-server
    restart: unless-stopped
    networks:
      - truco-network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: truco-client
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - truco-network
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dokploy-network"
      - "traefik.http.routers.truco-uruguayo.rule=Host(\"truco.peluguay.es\")"
      - "traefik.http.routers.truco-uruguayo.entrypoints=web,websecure"
      - "traefik.http.routers.truco-uruguayo.tls=true"
      - "traefik.http.routers.truco-uruguayo.tls.certresolver=letsencrypt"
      - "traefik.http.services.truco-uruguayo.loadbalancer.server.port=80"

networks:
  truco-network:
    driver: bridge
  dokploy-network:
    external: true
